In [1]:
import numpy as np

In [2]:
def cholesky_decomposition(matrix):
    
    # Ensure the matrix is square
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Matrix must be square")

    # Ensure the matrix is positive definite
    if not np.all(np.linalg.eigvals(matrix) > 0):
        raise ValueError("Matrix must be positive definite")

    n = matrix.shape[0]
    L = np.zeros_like(matrix)

    for i in range(n):
        for j in range(i + 1):
            if i == j:
                L[i, j] = np.sqrt(matrix[i, i] - np.sum(L[i, :j] ** 2))
            else:
                L[i, j] = (matrix[i, j] - np.sum(L[i, :j] * L[j, :j])) / L[j, j]

    return L

In [3]:
# Example usage:
if __name__ == "__main__":
    A = np.array([[4, 12, -16],
                  [12, 37, -43],
                  [-16, -43, 98]])

    try:
        L = cholesky_decomposition(A)
        print("Cholesky decomposition (L):\n", L)
        print("Verification (L * L.T):\n", np.dot(L, L.T))
    except ValueError as e:
        print(e)

Cholesky decomposition (L):
 [[ 2  0  0]
 [ 6  1  0]
 [-8  5  3]]
Verification (L * L.T):
 [[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]
