In [1]:
import numpy as np

def generate_positive_definite_matrix(n):
    """Generates a random n x n positive definite matrix."""
    A = np.random.rand(n, n)
    return np.dot(A, A.T) + n * np.eye(n)

def cholesky_decomposition(A):
    """Performs the Cholesky decomposition of a positive definite matrix A."""
    L = np.linalg.cholesky(A)
    return L

def main():
    n = 4  # Size of the matrix
    A = generate_positive_definite_matrix(n)
    print("Generated Positive Definite Matrix (A):")
    print(A)
    
    L = cholesky_decomposition(A)
    print("\nCholesky Decomposition (L):")
    print(L)
    
    LLT = np.dot(L, L.T)
    print("\nReconstructed Matrix from L * L.T:")
    print(LLT)
    
    # Inverse of L
    L_inv = np.linalg.inv(L)
    print("\nInverse of L (L_inv):")
    print(L_inv)
    
    # Product of L and its inverse (should be the identity matrix)
    identity_check = np.dot(L, L_inv)
    print("\nProduct of L and L_inv (should be identity matrix):")
    print(identity_check)

if __name__ == "__main__":
    main()


Generated Positive Definite Matrix (A):
[[5.72221242 1.10331133 1.34854309 0.64505435]
 [1.10331133 4.9339201  0.97305603 0.47093196]
 [1.34854309 0.97305603 5.33347825 0.40990544]
 [0.64505435 0.47093196 0.40990544 4.36556528]]

Cholesky Decomposition (L):
[[2.39211463 0.         0.         0.        ]
 [0.46122845 2.17282959 0.         0.        ]
 [0.56374518 0.32816228 2.21539593 0.        ]
 [0.26965863 0.15949604 0.09278075 2.06368657]]

Reconstructed Matrix from L * L.T:
[[5.72221242 1.10331133 1.34854309 0.64505435]
 [1.10331133 4.9339201  0.97305603 0.47093196]
 [1.34854309 0.97305603 5.33347825 0.40990544]
 [0.64505435 0.47093196 0.40990544 4.36556528]]

Inverse of L (L_inv):
[[ 0.41804017  0.          0.          0.        ]
 [-0.08873775  0.46022937  0.          0.        ]
 [-0.09323288 -0.06817288  0.45138658  0.        ]
 [-0.04357474 -0.03250476 -0.02029377  0.48456971]]

Product of L and L_inv (should be identity matrix):
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+

In [3]:

import numpy as np

def cholesky_decomposition(A):
    """
    Perform Cholesky decomposition of a matrix A.
    A must be a positive definite matrix.
    
    Parameters:
    A (numpy.ndarray): The matrix to decompose.
    
    Returns:
    L (numpy.ndarray): The lower triangular matrix such that A = L L^T.
    """
    # Check if A is a square matrix
    if not (A.shape[0] == A.shape[1]):
        raise ValueError("Matrix must be square")
    
    # Check if A is symmetric
    if not np.allclose(A, A.T):
        raise ValueError("Matrix must be symmetric")
    
    n = A.shape[0]
    L = np.zeros_like(A)

    for i in range(n):
        for j in range(i + 1):
            if i == j:  # Diagonal elements
                sum_k = sum(L[i][k] ** 2 for k in range(j))
                diff = A[i][i] - sum_k
                if diff <= 0:
                    raise ValueError("Matrix is not positive definite")
                L[i][j] = np.sqrt(diff)
            else:
                sum_k = sum(L[i][k] * L[j][k] for k in range(j))
                L[i][j] = (A[i][j] - sum_k) / L[j][j]
                
    return L

# Example usage
A = np.array([[25, 15, -5],
              [15, 18,  0],
              [-5,  0, 11]], dtype=float)

try:
    L = cholesky_decomposition(A)
    print("L:")
    print(L)
    print("L @ L.T:")
    print(np.dot(L, L.T))  # This should be equal to the original matrix A
except ValueError as e:
    print(e)

L:
[[ 5.  0.  0.]
 [ 3.  3.  0.]
 [-1.  1.  3.]]
L @ L.T:
[[25. 15. -5.]
 [15. 18.  0.]
 [-5.  0. 11.]]
